### ISSUE TITLE
Anyone have this working in WordPress 4.9.4?

### ISSUE THREAD

**Issue by stevenschlossman** [MotorsportReg/calendar-wordpress#1]
The package could not be installed. No valid plugins were found.

**Comment by stevenschlossman** [comment]
Brian,
I downloaded another version at http://api.motorsportreg.com/wordpress/index.cfm and that one works.

**Comment by ghidinelli** [comment]
@stevenschlossman so the version on github didn't work but the packaged zip file did?

**Comment by stevenschlossman** [comment]
Correct. I downloaded the version from github. That failed. The version from MSReg worked.
BTW- Does National Capital Chapter have an ID that includes all the subaccounts?
